<?php

namespace Proxy\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Project extends \Entity\Project implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setIsSave($isSave)
    {
        $this->__load();
        return parent::setIsSave($isSave);
    }

    public function getIsSave()
    {
        $this->__load();
        return parent::getIsSave();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setRanking($ranking)
    {
        $this->__load();
        return parent::setRanking($ranking);
    }

    public function getRanking()
    {
        $this->__load();
        return parent::getRanking();
    }

    public function setZipCode($zipCode)
    {
        $this->__load();
        return parent::setZipCode($zipCode);
    }

    public function getZipCode()
    {
        $this->__load();
        return parent::getZipCode();
    }

    public function setCreationTime($creationTime)
    {
        $this->__load();
        return parent::setCreationTime($creationTime);
    }

    public function getCreationTime()
    {
        $this->__load();
        return parent::getCreationTime();
    }

    public function setTags($tags)
    {
        $this->__load();
        return parent::setTags($tags);
    }

    public function getTags()
    {
        $this->__load();
        return parent::getTags();
    }

    public function setStartDate($startDate)
    {
        $this->__load();
        return parent::setStartDate($startDate);
    }

    public function getStartDate()
    {
        $this->__load();
        return parent::getStartDate();
    }

    public function setDuration($duration)
    {
        $this->__load();
        return parent::setDuration($duration);
    }

    public function getDuration()
    {
        $this->__load();
        return parent::getDuration();
    }

    public function setListLength($listLength)
    {
        $this->__load();
        return parent::setListLength($listLength);
    }

    public function getListLength()
    {
        $this->__load();
        return parent::getListLength();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setCompleteTime($completeTime)
    {
        $this->__load();
        return parent::setCompleteTime($completeTime);
    }

    public function getCompleteTime()
    {
        $this->__load();
        return parent::getCompleteTime();
    }

    public function setVideoPreview($videoPreview)
    {
        $this->__load();
        return parent::setVideoPreview($videoPreview);
    }

    public function getVideoPreview()
    {
        $this->__load();
        return parent::getVideoPreview();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setVisibility($visibility)
    {
        $this->__load();
        return parent::setVisibility($visibility);
    }

    public function getVisibility()
    {
        $this->__load();
        return parent::getVisibility();
    }

    public function setShowCountry($showCountry)
    {
        $this->__load();
        return parent::setShowCountry($showCountry);
    }

    public function getShowCountry()
    {
        $this->__load();
        return parent::getShowCountry();
    }

    public function setShowCity($showCity)
    {
        $this->__load();
        return parent::setShowCity($showCity);
    }

    public function getShowCity()
    {
        $this->__load();
        return parent::getShowCity();
    }

    public function setShowAudioPreview($showAudioPreview)
    {
        $this->__load();
        return parent::setShowAudioPreview($showAudioPreview);
    }

    public function getShowAudioPreview()
    {
        $this->__load();
        return parent::getShowAudioPreview();
    }

    public function setShowTags($showTags)
    {
        $this->__load();
        return parent::setShowTags($showTags);
    }

    public function getShowTags()
    {
        $this->__load();
        return parent::getShowTags();
    }

    public function setShowDescription($showDescription)
    {
        $this->__load();
        return parent::setShowDescription($showDescription);
    }

    public function getShowDescription()
    {
        $this->__load();
        return parent::getShowDescription();
    }

    public function setShowLanguage($showLanguage)
    {
        $this->__load();
        return parent::setShowLanguage($showLanguage);
    }

    public function getShowLanguage()
    {
        $this->__load();
        return parent::getShowLanguage();
    }

    public function setShowStartDate($showStartDate)
    {
        $this->__load();
        return parent::setShowStartDate($showStartDate);
    }

    public function getShowStartDate()
    {
        $this->__load();
        return parent::getShowStartDate();
    }

    public function setShowDuration($showDuration)
    {
        $this->__load();
        return parent::setShowDuration($showDuration);
    }

    public function getShowDuration()
    {
        $this->__load();
        return parent::getShowDuration();
    }

    public function setShowListLength($showListLength)
    {
        $this->__load();
        return parent::setShowListLength($showListLength);
    }

    public function getShowListLength()
    {
        $this->__load();
        return parent::getShowListLength();
    }

    public function setShowVideoPreview($showVideoPreview)
    {
        $this->__load();
        return parent::setShowVideoPreview($showVideoPreview);
    }

    public function getShowVideoPreview()
    {
        $this->__load();
        return parent::getShowVideoPreview();
    }

    public function setLastEditTime($lastEditTime)
    {
        $this->__load();
        return parent::setLastEditTime($lastEditTime);
    }

    public function getLastEditTime()
    {
        $this->__load();
        return parent::getLastEditTime();
    }

    public function addAudition(\Entity\Audition $auditions)
    {
        $this->__load();
        return parent::addAudition($auditions);
    }

    public function removeAudition(\Entity\Audition $auditions)
    {
        $this->__load();
        return parent::removeAudition($auditions);
    }

    public function getAuditions()
    {
        $this->__load();
        return parent::getAuditions();
    }

    public function addSkill(\Entity\ProjectSkill $skills)
    {
        $this->__load();
        return parent::addSkill($skills);
    }

    public function removeSkill(\Entity\ProjectSkill $skills)
    {
        $this->__load();
        return parent::removeSkill($skills);
    }

    public function getSkills()
    {
        $this->__load();
        return parent::getSkills();
    }

    public function addMember(\Entity\ProjectMember $members)
    {
        $this->__load();
        return parent::addMember($members);
    }

    public function removeMember(\Entity\ProjectMember $members)
    {
        $this->__load();
        return parent::removeMember($members);
    }

    public function getMembers()
    {
        $this->__load();
        return parent::getMembers();
    }

    public function addFile(\Entity\ProjectFile $files)
    {
        $this->__load();
        return parent::addFile($files);
    }

    public function removeFile(\Entity\ProjectFile $files)
    {
        $this->__load();
        return parent::removeFile($files);
    }

    public function getFiles()
    {
        $this->__load();
        return parent::getFiles();
    }

    public function addContract(\Entity\Contract $contracts)
    {
        $this->__load();
        return parent::addContract($contracts);
    }

    public function removeContract(\Entity\Contract $contracts)
    {
        $this->__load();
        return parent::removeContract($contracts);
    }

    public function getContracts()
    {
        $this->__load();
        return parent::getContracts();
    }

    public function setCountry(\Entity\Country $country = NULL)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setState(\Entity\USState $state = NULL)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setOwner(\Entity\User $owner = NULL)
    {
        $this->__load();
        return parent::setOwner($owner);
    }

    public function getOwner()
    {
        $this->__load();
        return parent::getOwner();
    }

    public function setPhoto(\Entity\ProjectFile $photo = NULL)
    {
        $this->__load();
        return parent::setPhoto($photo);
    }

    public function getPhoto()
    {
        $this->__load();
        return parent::getPhoto();
    }

    public function setLanguage(\Entity\Language $language = NULL)
    {
        $this->__load();
        return parent::setLanguage($language);
    }

    public function getLanguage()
    {
        $this->__load();
        return parent::getLanguage();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'isSave', 'city', 'ranking', 'zipCode', 'creationTime', 'tags', 'startDate', 'duration', 'listLength', 'description', 'completeTime', 'videoPreview', 'status', 'visibility', 'showCountry', 'showCity', 'showAudioPreview', 'showTags', 'showDescription', 'showLanguage', 'showStartDate', 'showDuration', 'showListLength', 'showVideoPreview', 'lastEditTime', 'auditions', 'skills', 'members', 'files', 'contracts', 'country', 'state', 'owner', 'photo', 'language');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}