<?php

namespace Proxy\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setCreationTime($creationTime)
    {
        $this->__load();
        return parent::setCreationTime($creationTime);
    }

    public function getCreationTime()
    {
        $this->__load();
        return parent::getCreationTime();
    }

    public function setRegistrationIP($registrationIP)
    {
        $this->__load();
        return parent::setRegistrationIP($registrationIP);
    }

    public function getRegistrationIP()
    {
        $this->__load();
        return parent::getRegistrationIP();
    }

    public function setLastLoginIP($lastLoginIP)
    {
        $this->__load();
        return parent::setLastLoginIP($lastLoginIP);
    }

    public function getLastLoginIP()
    {
        $this->__load();
        return parent::getLastLoginIP();
    }

    public function setLastLoginTime($lastLoginTime)
    {
        $this->__load();
        return parent::setLastLoginTime($lastLoginTime);
    }

    public function getLastLoginTime()
    {
        $this->__load();
        return parent::getLastLoginTime();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setDob($dob)
    {
        $this->__load();
        return parent::setDob($dob);
    }

    public function getDob()
    {
        $this->__load();
        return parent::getDob();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setPrivacy($privacy)
    {
        $this->__load();
        return parent::setPrivacy($privacy);
    }

    public function getPrivacy()
    {
        $this->__load();
        return parent::getPrivacy();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setZipCode($zipCode)
    {
        $this->__load();
        return parent::setZipCode($zipCode);
    }

    public function getZipCode()
    {
        $this->__load();
        return parent::getZipCode();
    }

    public function setUnreadThread($unreadThread)
    {
        $this->__load();
        return parent::setUnreadThread($unreadThread);
    }

    public function getUnreadThread()
    {
        $this->__load();
        return parent::getUnreadThread();
    }

    public function setWebAddress($webAddress)
    {
        $this->__load();
        return parent::setWebAddress($webAddress);
    }

    public function getWebAddress()
    {
        $this->__load();
        return parent::getWebAddress();
    }

    public function setBiography($biography)
    {
        $this->__load();
        return parent::setBiography($biography);
    }

    public function getBiography()
    {
        $this->__load();
        return parent::getBiography();
    }

    public function setAgentName($agentName)
    {
        $this->__load();
        return parent::setAgentName($agentName);
    }

    public function getAgentName()
    {
        $this->__load();
        return parent::getAgentName();
    }

    public function setAgentEmail($agentEmail)
    {
        $this->__load();
        return parent::setAgentEmail($agentEmail);
    }

    public function getAgentEmail()
    {
        $this->__load();
        return parent::getAgentEmail();
    }

    public function setAgentPhone($agentPhone)
    {
        $this->__load();
        return parent::setAgentPhone($agentPhone);
    }

    public function getAgentPhone()
    {
        $this->__load();
        return parent::getAgentPhone();
    }

    public function setManagerName($managerName)
    {
        $this->__load();
        return parent::setManagerName($managerName);
    }

    public function getManagerName()
    {
        $this->__load();
        return parent::getManagerName();
    }

    public function setManagerEmail($managerEmail)
    {
        $this->__load();
        return parent::setManagerEmail($managerEmail);
    }

    public function getManagerEmail()
    {
        $this->__load();
        return parent::getManagerEmail();
    }

    public function setManagerPhone($managerPhone)
    {
        $this->__load();
        return parent::setManagerPhone($managerPhone);
    }

    public function getManagerPhone()
    {
        $this->__load();
        return parent::getManagerPhone();
    }

    public function setBookingName($bookingName)
    {
        $this->__load();
        return parent::setBookingName($bookingName);
    }

    public function getBookingName()
    {
        $this->__load();
        return parent::getBookingName();
    }

    public function setBookingEmail($bookingEmail)
    {
        $this->__load();
        return parent::setBookingEmail($bookingEmail);
    }

    public function getBookingEmail()
    {
        $this->__load();
        return parent::getBookingEmail();
    }

    public function setBookingPhone($bookingPhone)
    {
        $this->__load();
        return parent::setBookingPhone($bookingPhone);
    }

    public function getBookingPhone()
    {
        $this->__load();
        return parent::getBookingPhone();
    }

    public function setPublisherName($publisherName)
    {
        $this->__load();
        return parent::setPublisherName($publisherName);
    }

    public function getPublisherName()
    {
        $this->__load();
        return parent::getPublisherName();
    }

    public function setPublisherEmail($publisherEmail)
    {
        $this->__load();
        return parent::setPublisherEmail($publisherEmail);
    }

    public function getPublisherEmail()
    {
        $this->__load();
        return parent::getPublisherEmail();
    }

    public function setPublisherPhone($publisherPhone)
    {
        $this->__load();
        return parent::setPublisherPhone($publisherPhone);
    }

    public function getPublisherPhone()
    {
        $this->__load();
        return parent::getPublisherPhone();
    }

    public function setRecordName($recordName)
    {
        $this->__load();
        return parent::setRecordName($recordName);
    }

    public function getRecordName()
    {
        $this->__load();
        return parent::getRecordName();
    }

    public function setRecordWebsite($recordWebsite)
    {
        $this->__load();
        return parent::setRecordWebsite($recordWebsite);
    }

    public function getRecordWebsite()
    {
        $this->__load();
        return parent::getRecordWebsite();
    }

    public function setPWL($pWL)
    {
        $this->__load();
        return parent::setPWL($pWL);
    }

    public function getPWL()
    {
        $this->__load();
        return parent::getPWL();
    }

    public function setFBL($fBL)
    {
        $this->__load();
        return parent::setFBL($fBL);
    }

    public function getFBL()
    {
        $this->__load();
        return parent::getFBL();
    }

    public function setTWL($tWL)
    {
        $this->__load();
        return parent::setTWL($tWL);
    }

    public function getTWL()
    {
        $this->__load();
        return parent::getTWL();
    }

    public function setSCL($sCL)
    {
        $this->__load();
        return parent::setSCL($sCL);
    }

    public function getSCL()
    {
        $this->__load();
        return parent::getSCL();
    }

    public function setPwToken($pwToken)
    {
        $this->__load();
        return parent::setPwToken($pwToken);
    }

    public function getPwToken()
    {
        $this->__load();
        return parent::getPwToken();
    }

    public function setPwTokenCreationTime($pwTokenCreationTime)
    {
        $this->__load();
        return parent::setPwTokenCreationTime($pwTokenCreationTime);
    }

    public function getPwTokenCreationTime()
    {
        $this->__load();
        return parent::getPwTokenCreationTime();
    }

    public function setProfilePicture(\Entity\File $profilePicture = NULL)
    {
        $this->__load();
        return parent::setProfilePicture($profilePicture);
    }

    public function getProfilePicture()
    {
        $this->__load();
        return parent::getProfilePicture();
    }

    public function setCoverPhoto(\Entity\File $coverPhoto = NULL)
    {
        $this->__load();
        return parent::setCoverPhoto($coverPhoto);
    }

    public function getCoverPhoto()
    {
        $this->__load();
        return parent::getCoverPhoto();
    }

    public function setFB(\Entity\Facebook $fB = NULL)
    {
        $this->__load();
        return parent::setFB($fB);
    }

    public function getFB()
    {
        $this->__load();
        return parent::getFB();
    }

    public function setTW(\Entity\Twitter $tW = NULL)
    {
        $this->__load();
        return parent::setTW($tW);
    }

    public function getTW()
    {
        $this->__load();
        return parent::getTW();
    }

    public function addProject(\Entity\ProjectMember $projects)
    {
        $this->__load();
        return parent::addProject($projects);
    }

    public function removeProject(\Entity\ProjectMember $projects)
    {
        $this->__load();
        return parent::removeProject($projects);
    }

    public function getProjects()
    {
        $this->__load();
        return parent::getProjects();
    }

    public function addFile(\Entity\File $files)
    {
        $this->__load();
        return parent::addFile($files);
    }

    public function removeFile(\Entity\File $files)
    {
        $this->__load();
        return parent::removeFile($files);
    }

    public function getFiles()
    {
        $this->__load();
        return parent::getFiles();
    }

    public function addAudition(\Entity\Audition $auditions)
    {
        $this->__load();
        return parent::addAudition($auditions);
    }

    public function removeAudition(\Entity\Audition $auditions)
    {
        $this->__load();
        return parent::removeAudition($auditions);
    }

    public function getAuditions()
    {
        $this->__load();
        return parent::getAuditions();
    }

    public function addMessageSent(\Entity\Message $messageSent)
    {
        $this->__load();
        return parent::addMessageSent($messageSent);
    }

    public function removeMessageSent(\Entity\Message $messageSent)
    {
        $this->__load();
        return parent::removeMessageSent($messageSent);
    }

    public function getMessageSent()
    {
        $this->__load();
        return parent::getMessageSent();
    }

    public function addSkill(\Entity\UserSkill $skills)
    {
        $this->__load();
        return parent::addSkill($skills);
    }

    public function removeSkill(\Entity\UserSkill $skills)
    {
        $this->__load();
        return parent::removeSkill($skills);
    }

    public function getSkills()
    {
        $this->__load();
        return parent::getSkills();
    }

    public function addThread(\Entity\ThreadUser $threads)
    {
        $this->__load();
        return parent::addThread($threads);
    }

    public function removeThread(\Entity\ThreadUser $threads)
    {
        $this->__load();
        return parent::removeThread($threads);
    }

    public function getThreads()
    {
        $this->__load();
        return parent::getThreads();
    }

    public function addMyProject(\Entity\Project $myProjects)
    {
        $this->__load();
        return parent::addMyProject($myProjects);
    }

    public function removeMyProject(\Entity\Project $myProjects)
    {
        $this->__load();
        return parent::removeMyProject($myProjects);
    }

    public function getMyProjects()
    {
        $this->__load();
        return parent::getMyProjects();
    }

    public function setCountry(\Entity\Country $country = NULL)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setState(\Entity\USState $state = NULL)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setLanguage(\Entity\Language $language = NULL)
    {
        $this->__load();
        return parent::setLanguage($language);
    }

    public function getLanguage()
    {
        $this->__load();
        return parent::getLanguage();
    }

    public function addContact(\Entity\User $contacts)
    {
        $this->__load();
        return parent::addContact($contacts);
    }

    public function removeContact(\Entity\User $contacts)
    {
        $this->__load();
        return parent::removeContact($contacts);
    }

    public function getContacts()
    {
        $this->__load();
        return parent::getContacts();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'password', 'firstName', 'lastName', 'email', 'creationTime', 'registrationIP', 'lastLoginIP', 'lastLoginTime', 'status', 'dob', 'gender', 'privacy', 'city', 'zipCode', 'unreadThread', 'webAddress', 'biography', 'agentName', 'agentEmail', 'agentPhone', 'managerName', 'managerEmail', 'managerPhone', 'bookingName', 'bookingEmail', 'bookingPhone', 'publisherName', 'publisherEmail', 'publisherPhone', 'recordName', 'recordWebsite', 'PWL', 'FBL', 'TWL', 'SCL', 'pwToken', 'pwTokenCreationTime', 'profilePicture', 'coverPhoto', 'FB', 'TW', 'projects', 'files', 'auditions', 'messageSent', 'skills', 'threads', 'myProjects', 'country', 'state', 'language', 'contacts');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}