<html>
	<body style="font-family: helvetica; font-size: 14px; width: 600px; line-height: 20px; height: 683px;">
		<div style="width: 600px; height: 660px;  background-color: #282828;">
			<ul style="list-style-type: none; margin: 0px;	padding: 0px;">
				<li style="height: 40px;  background-color: #282828;  text-indent: 40px;  line-height: 40px;  font-size: 12px;  color: #696969;">
					<div style="width: 200px;  float: left;  height: inherit;  background-image: url('<?= base_url('img/email_template/calender.png')?>');  background-repeat: no-repeat;  background-position-y: 5px; line-height: 26px;">
						<?= date('l, F d', time()) ?>
					</div>
					<div style="width: 200px;  float: right;  height: inherit;">
						<a href="mailto:info@findmysong.com" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(105, 105, 105);  cursor: auto;  display: inline;  font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: auto;  line-height: 40px;  list-style-type: none;  text-align: left;  text-decoration: none;  text-indent: 40px;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
							info@findmysong.com
						</a>
					</div>
				</li>
				<li style="width: 600px; height: 577px; background-color: #ECECEC; border-top-left-radius: 8px;  border-top-right-radius: 8px; border-bottom-left-radius: 8px;  border-bottom-right-radius: 8px; margin-left: 0px;">
					<div style="-webkit-background-size: 600px; background-image: url('<?= base_url('img/email_template/fms-logo-black.png')?>');  background-repeat: no-repeat;  background-size: 170px;  border-top-left-radius: 8px;  border-top-right-radius: 8px;  color: #B7B7B7;  display: list-item;  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 165px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 600px;background-color: #ECECEC;background-position-x: 15px;background-position-y: 20px;">
						<div style="color: rgb(69, 69, 69);  display: block;  float: right;  font-family:  'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 70px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 253px;">
							<ul style="color: rgb(69, 69, 69);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 0px;  line-height: 20px;  list-style-type: none;  margin-bottom: 0px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-bottom: 0px;  padding-left: 0px;  padding-right: 0px;  padding-top: 0px;  text-align: left;  width: 253px;">
								<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: 70px;  line-height: 70px;  list-style-type: none;  text-align: left;  width: 70px; margin-left: 0px;">
									<a href="<?= base_url()?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: #B7B7B7;  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: auto;  line-height: 70px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">HOME</a></li>
								<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: 70px;  line-height: 70px;  list-style-type: none;  text-align: left;  width: 90px; margin-left: 0px;">
									<a href="<?= base_url('about')?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: #B7B7B7;  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: auto;  line-height: 70px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">ABOUT US</a></li>
								<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: 70px;  line-height: 70px;  list-style-type: none;  text-align: left;  width: 90px; margin-left: 0px;">
									<a href="<?= base_url('contact')?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: #B7B7B7;  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: auto;  line-height: 70px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">CONTACT</a></li>
							</ul>
						</div>
						<div style="color: rgb(0, 0, 0);  display: block;  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 25px;  font-weight: 100;  height: 40px;  line-height: 20px;  list-style-type: none;  padding-top: 100px;  text-align: center;  width: 600px;">Password Reset Instructions</div>
					</div>
					
					<div style="background-color: rgb(255, 255, 255); border: 1px solid; border-color: #DBDBDB; color: rgb(105, 105, 105);  display: list-item;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 290px; line-height: 20px;list-style-type: none;  padding-left: 15px;  padding-right: 15px;  text-align: left;  width: 538px;margin-top: -14px; margin-left: 15px;">
						<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 18px;  font-weight: 300;  height: 22px;  line-height: 22px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-top: 25px;  text-align: left;  width: 530px;">
							Hello <span style="color: rgb(103, 164, 245);  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 18px;  font-weight: 300;  height: auto;  line-height: 22px;  list-style-type: none;  text-align: left;  width: auto;">
								<?= $userName ?>,</span>
						</p>
						<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 16px;  font-weight: 300;  height: 65px; list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  text-align: left;  width: 530px;">  
							You (or someone pretending to be you) has requested to reset your password on FindMySong. 
							If you would like to continue, please <a href="<?=$link?>" style="-webkit-backface-visibility: hidden; -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: #2985CA;  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 16px; height: auto; list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">click here </a>.
						</p>
						<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 16px;  font-weight: 300;  height: 60px; list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  text-align: left;  width: 530px;">
							If this wasn&#146;t you or you&#146;d like to keep your same password, simply ignore this email.
						</p>
						<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 16px;  font-weight: 300;  height: 13px; list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  text-align: left;  width: 530px;">
							Have a great day!
						</p>
						<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 16px;  font-weight: 300;  height: 40px; list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  text-align: left;  width: 530px;">
							The FMS Team
						</p>
					</div>
					
					<div style="  background-color: #ECECEC; margin-top: -14px; background-image: url('<?= base_url('img/email_template/fms-logo-black.png') ?>');  background-repeat: no-repeat;  border-bottom-left-radius: 8px;  border-bottom-right-radius: 8px;  color: rgb(69, 69, 69);  display: list-item;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 130px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 600px; background-position-x: 20px;  background-position-y: 30px; background-size: 20%;">
						<ul style="  color: rgb(69, 69, 69);  display: block;  float: right;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 70px;  line-height: 20px;  list-style-type: none;  margin-bottom: 0px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-bottom: 0px;  padding-left: 0px;  padding-right: 0px;  padding-top: 0px;  text-align: left;  width: 150px; display: block;  float: right;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 70px;  line-height: 20px;  list-style-type: none;  margin-bottom: 0px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-bottom: 0px;  padding-left: 0px;  padding-right: 0px;  padding-top: 0px;  text-align: left;  width: 150px;">
							<li style="  color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 50px;  line-height: 20px;  list-style-type: none;  margin-top: 20px;  text-align: left;  width: 50px;display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 50px;  line-height: 20px;  list-style-type: none;  margin-top: 20px;  text-align: left;  width: 50px;margin-left: 0px;">
								<a href="https://www.facebook.com/FindMySong" style="  -webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
									<img src="<?= base_url('img/email_template/facebook.png')?>" style="  border-bottom-color: rgb(35, 112, 171);                                                          border-bottom-style: none;  border-bottom-width: 0px;  border-image-outset: 0px;  border-image-repeat: stretch;  border-image-slice: 100%;  border-image-source: none;  border-image-width: 1;  border-left-color: rgb(35, 112, 171);  border-left-style: none;  border-left-width: 0px;  border-right-color: rgb(35, 112, 171);  border-right-style: none;  border-right-width: 0px;  border-top-color: rgb(35, 112, 171);  border-top-style: none;  border-top-width: 0px;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 40px;  line-height: 20px;  list-style-type: none;  max-width: 100%;  text-align: left;  vertical-align: middle;  width: 40px;">
								</a>
							</li>
							<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 50px;  line-height: 20px;  list-style-type: none;  margin-top: 20px;  text-align: left;  width: 50px; margin-left: 0px;">
								<a href="https://twitter.com/FindMySong" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
									<img src="<?= base_url('img/email_template/twitter.png')?>">
								</a>
							</li>
							<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 50px;  line-height: 20px;  list-style-type: none;  margin-top: 20px;  text-align: left;  width: 50px; margin-left: 0px;">
								<a href=" http://www.linkedin.com/company/find-my-song-llc-" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
									<img src="<?= base_url('img/email_template/linkedIn.png')?>">
								</a>
							</li>
						</ul>
						<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: 20px;  line-height: 20px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 15px;  padding-left: 22px;  padding-top: 90px;  text-align: center;  width: 578px;"><span style="color: rgb(103, 164, 245);  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: center;  width: auto;">Address</span> : 2222 S. Figueroa St. #215 Los Angeles, CA 90007 </p>
					</div>
				</li>
				<li style="background-color: rgb(39, 39, 39);  color: rgb(255, 255, 255);  display: list-item;  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: 55px;  line-height: 60px;  list-style-type: none;  text-align: center;  width: 600px; margin-left: 0px;">
					FindMySong LLC &#169; Copyright 2013  All Rights Reserved
				</li>
			</ul>
		</div>
	</body>
</html>