<html>
	<body style="font-family: helvetica; font-size: 14px; width: 500px; line-height: 20px;">
		<div style="width: 600px; height: 1448px;  background-color: #282828;">
			<ul style="list-style-type: none; margin: 0px;	padding: 0px;">
				<li style="height: 40px;  background-color: #282828;  text-indent: 40px;  line-height: 40px;  font-size: 12px;  color: #696969;">
					<div style="width: 200px;  float: left;  height: inherit;  background-image: url('<?= base_url('img/email_template/calender.png')?>');  background-repeat: no-repeat;  background-position-y: 5px;  background-position-x: 10px;">
						<?= date('l, F d', time()) ?>
					</div>
					<div style="width: 200px;  float: right;  height: inherit;">
						<a href="mailto:info@findmysong.com" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(105, 105, 105);  cursor: auto;  display: inline;  font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: auto;  line-height: 40px;  list-style-type: none;  text-align: left;  text-decoration: none;  text-indent: 40px;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
							info@findmysong.com
						</a>
					</div>
				</li>
				<li style="-webkit-background-size: 600px; background-image: url('<?= base_url('img/email_template/email_header_with_header.jpg')?>');  background-repeat: no-repeat;  background-size: 600px;  border-top-left-radius: 8px;  border-top-right-radius: 8px;  color: rgb(69, 69, 69);  display: list-item;  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 310px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 600px; margin-left: 0px; background-size: 100%;">
					<div style="color: rgb(69, 69, 69);  display: block;  float: right;  font-family:  'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 70px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 295px;">
						<ul style="color: rgb(69, 69, 69);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 0px;  line-height: 20px;  list-style-type: none;  margin-bottom: 0px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-bottom: 0px;  padding-left: 0px;  padding-right: 0px;  padding-top: 0px;  text-align: left;  width: 295px;">
							<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: 70px;  line-height: 70px;  list-style-type: none;  text-align: left;  width: 70px;">
								<a href="<?= base_url()?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(255, 255, 255);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: auto;  line-height: 70px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">HOME</a></li>
							<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: 70px;  line-height: 70px;  list-style-type: none;  text-align: left;  width: 90px;">
								<a href="<?= base_url('about')?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(255, 255, 255);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: auto;  line-height: 70px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">ABOUT US</a></li>
							<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: 70px;  line-height: 70px;  list-style-type: none;  text-align: left;  width: 90px;">
								<a href="<?= base_url('contact')?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(255, 255, 255);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 13px;  font-weight: bold;  height: auto;  line-height: 70px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">CONTACT</a></li>
						</ul>
					</div>
				</li>
				<li style="background-color: rgb(51, 51, 51);  color: rgb(105, 105, 105);  display: list-item;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 240px;line-height: 20px;list-style-type: none;  padding-left: 35px;  padding-right: 35px;  text-align: left;  width: 530px;margin-left: 0px; margin-bottom: -10px;">
					<p style="0.25px;  color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 24px;  font-weight: 300;  height: 22px;  line-height: 22px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-top: 32px;  text-align: left;  width: 530px;">
						Hi <span style="color: rgb(103, 164, 245);  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 24px;  font-weight: 300;  height: auto;  line-height: 22px;  list-style-type: none;  text-align: left;  width: auto;">
							<?= $userName ?>,</span>
					</p>
					<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 15px;  font-weight: 300;  height: 110px;  line-height: 22px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-top: 10px;  text-align: left;  width: 530px;">Thanks for joining the community at FindMySong!  
						As the fastest-growing music collaboration site on the Internet, 
						there&#146;s a lot of opportunity to get involved.  
						We want you to get the most out of it, so here&#146;s some helpful 
						information perfect for new members just like you.
					</p>
				</li>
				<li style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 18px;  font-weight: 300;  height: 398px;  line-height: 22px;  list-style-type: none;    margin-left: 0px;  margin-right: 0px;  margin-top: 0px;padding-top: 10px;  text-align: left;width: 600px;">
					<ul style="color: rgb(69, 69, 69);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 422px;  line-height: 20px;  list-style-type: none;  margin-bottom: 0px;  margin-left: 0px;  margin-right: 0px;    padding-bottom: 0px;  padding-left: 0px;  padding-right: 0px;  padding-top: 0px;  text-align: left;  width: 600px;margin-top: -10px;">
						<li style="background-color: rgb(255, 255, 255);  color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 422px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 200px; margin-left: 0px;">
							<a href="<?= base_url('users/profile/' . $userId) ?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
								<img src="<?= base_url('img/email_template/profile.png')?>" style="border-bottom-color: rgb(35, 112, 171);  border-bottom-style: none;  border-bottom-width: 0px;  border-image-outset: 0px;  border-image-repeat: stretch;  border-image-slice: 100%;  border-image-source: none;  border-image-width: 1;  border-left-color: rgb(35, 112, 171);  border-left-style: none;  border-left-width: 0px;  border-right-color: rgb(35, 112, 171);  border-right-style: none;  border-right-width: 0px;  border-top-color: rgb(35, 112, 171);  border-top-style: none;  border-top-width: 0px;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 120px;  line-height: 20px;  list-style-type: none;  max-width: 100%;  padding-left: 40px;  padding-top: 40px;  text-align: left;  vertical-align: middle;  width: 120px;">
							</a>
							<p style="color: rgb(103, 164, 245);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 15px;  font-weight: normal;  height: 25px;  line-height: 25px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 20px;  padding-top: 40px;  text-align: center;  width: 160px;">YOUR PROFILE</p>
							<p style="color: rgb(129, 129, 129);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: 140px;  line-height: 20px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 20px;  text-align: center;  width: 160px;">Your profile has been expertly-designed to showcase you and your work.  
								Completing your profile helps other musicians find you on FindMySong 
								and makes a great resume.
							</p>
						</li>
						<li style="background-color: rgb(255, 255, 255);  color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 422px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 200px; margin-left: 0px;">
							<a href="<?= base_url('dashboard/project') ?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
								<img src="<?= base_url('img/email_template/project.png')?>" style="border-bottom-color: rgb(35, 112, 171);  border-bottom-style: none;  border-bottom-width: 0px;  border-image-outset: 0px;  border-image-repeat: stretch;  border-image-slice: 100%;  border-image-source: none;  border-image-width: 1;  border-left-color: rgb(35, 112, 171);  border-left-style: none;  border-left-width: 0px;  border-right-color: rgb(35, 112, 171);  border-right-style: none;  border-right-width: 0px;  border-top-color: rgb(35, 112, 171);  border-top-style: none;  border-top-width: 0px;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 120px;  line-height: 20px;  list-style-type: none;  max-width: 100%;  padding-left: 40px;  padding-top: 40px;  text-align: left;  vertical-align: middle;  width: 120px;">
							</a>
							<p style="color: rgb(103, 164, 245);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 15px;  font-weight: normal;  height: 25px;  line-height: 25px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 20px;  padding-top: 40px;  text-align: center;  width: 160px;">YOUR PROJECTS</p>
							<p style="color: rgb(129, 129, 129);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: 160px;  line-height: 20px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 20px;  text-align: center;  width: 160px;">We created projects to help you stay organized online while you work.  
								Work with your friends, audition new musicians, save your split sheets, 
								and keep your professional network looped in.
							</p>
						</li>
						<li style="background-color: rgb(255, 255, 255);  color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 422px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 200px; margin-left: 0px;">
							<a href="<?= base_url('users/search') ?>" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
								<img src="<?= base_url('img/email_template/network.png')?>" style="border-bottom-color: rgb(35, 112, 171);  border-bottom-style: none;  border-bottom-width: 0px;  border-image-outset: 0px;  border-image-repeat: stretch;  border-image-slice: 100%;  border-image-source: none;  border-image-width: 1;  border-left-color: rgb(35, 112, 171);  border-left-style: none;  border-left-width: 0px;  border-right-color: rgb(35, 112, 171);  border-right-style: none;  border-right-width: 0px;  border-top-color: rgb(35, 112, 171);  border-top-style: none;  border-top-width: 0px;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 120px;  line-height: 20px;  list-style-type: none;  max-width: 100%;  padding-left: 40px;  padding-top: 40px;  text-align: left;  vertical-align: middle;  width: 120px;">
							</a>
							<p style="color: rgb(103, 164, 245);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 15px;  font-weight: normal;  height: 25px;  line-height: 25px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 20px;  padding-top: 40px;  text-align: center;  width: 160px;">YOUR NETWORK</p>
							<p style="color: rgb(129, 129, 129);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: 140px;  line-height: 20px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 20px;  text-align: center;  width: 160px;">We are a home for musicians, songwriters, engineers, fans, and people 
								passionate about making music from all around the world. 
								Find new people, or work with your friends.
							</p>
						</li>
					</ul>
				</li>
				<li style="background-color: rgb(236, 236, 236);  color: rgb(69, 69, 69);  display: list-item;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 242px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 600px; margin-left: 0px;">
					<p style="color: rgb(0, 0, 0);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: 300;  height: 40px;  line-height: 20px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-bottom: 15px;  padding-left: 20px;  padding-right: 40px;  padding-top: 40px;  text-align: left;  width: 540px;">We hope you enjoy using FindMySong.  
						If you have any questions or concerns at all, please email us anytime at 
						<a href="mailto:info@findmysong.com">info@findmysong.com</a>
					</p>
					<p style="color: rgb(0, 0, 0);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: 300;  height: 8px;  line-height: 8px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 33px;  text-align: left;  width: 547px;">Thanks,</p>
					<p style="color: rgb(0, 0, 0);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: 300;  height: 8px;  line-height: 8px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 33px;  text-align: left;  width: 547px;">The FMS Team</p>
					<p style="color: rgb(0, 0, 0);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: 300;  height: 40px;  line-height: 20px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 20px;  padding-right: 33px;  padding-top: 30px;  text-align: left;  width: 547px;">
						PS. Even if you don&#146;t have questions, we&#146;d love to meet you!  
						Reach out anytime to <a href="mailto:info@findmysong.com">info@findmysong.com</a>
					</p>
				</li>
				<li style=" background-color: rgb(216, 216, 216); margin-top: -14px;   background-image: url('<?= base_url('img/email_template/fms_HeaderLogo_beta.png') ?>');  background-repeat: no-repeat;  border-bottom-left-radius: 8px;  border-bottom-right-radius: 8px;  color: rgb(69, 69, 69);  display: list-item;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 160px;  line-height: 20px;  list-style-type: none;  text-align: left;  width: 600px; background-position-x: 20px;  background-position-y: 20px; margin-left: 0px; margin-top: -10px;">
					<ul style="color: rgb(69, 69, 69);  display: block;  float: right; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px;  font-weight: normal;  height: 50px;  line-height: 20px;  list-style-type: none; margin-bottom: 0px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-bottom: 0px;  padding-left: 0px;  padding-right: 0px;  padding-top: 0px;  text-align: left;  width: 150px;">
						<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 50px;  line-height: 20px;  list-style-type: none;  margin-top: 20px;  text-align: left;  width: 50px; margin-left: 0px;">
							<a href="https://twitter.com/FindMySong" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
								<img src="<?= base_url('img/email_template/facebook.png')?>">
							</a>
						</li>
						<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 50px;  line-height: 20px;  list-style-type: none;  margin-top: 20px;  text-align: left;  width: 50px; margin-left: 0px;">
							<a href="https://twitter.com/FindMySong" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
								<img src="<?= base_url('img/email_template/twitter.png')?>">
							</a>
						</li>
						<li style="color: rgb(69, 69, 69);  display: list-item;  float: left;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: 50px;  line-height: 20px;  list-style-type: none;  margin-top: 20px;  text-align: left;  width: 50px; margin-left: 0px;">
							<a href=" http://www.linkedin.com/company/find-my-song-llc-" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 14px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">
								<img src="<?= base_url('img/email_template/linkedIn.png')?>">
							</a>
						</li>
					</ul>
					<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: 20px;  line-height: 20px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 22px;  padding-top: 90px;  text-align: left;  width: 578px;"><span style="color: rgb(103, 164, 245);  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  width: auto;">Address</span> : 2222 S. Figueroa St. #215 Los Angeles, CA 90007 </p>
					<p style="color: rgb(93, 93, 93);  display: block;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: 20px;  line-height: 20px;  list-style-type: none;  margin-bottom: 10px;  margin-left: 0px;  margin-right: 0px;  margin-top: 0px;  padding-left: 22px;  text-align: left;  width: 578px;">You are currently signed up to FindMySong newsletters as <?php echo $userEmail; ?>. 
						<a href="&lt;?= base_url('unsubscribe')?&gt;" style="-webkit-backface-visibility: hidden;  -webkit-transition-delay: 0s;  -webkit-transition-duration: 0.25s;  -webkit-transition-property: all;  -webkit-transition-timing-function: ease;  color: rgb(35, 112, 171);  cursor: auto;  display: inline;  font-family:   'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: auto;  line-height: 20px;  list-style-type: none;  text-align: left;  text-decoration: none;  transition-delay: 0s;  transition-duration: 0.25s;  transition-property: all;  transition-timing-function: ease;  width: auto;">Click here to unsubscribe </a>
					</p>
				</li>
				<li style="background-color: rgb(39, 39, 39);  color: rgb(255, 255, 255);  display: list-item;  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;  font-size: 12px;  font-weight: normal;  height: 70px;  line-height: 75px;  list-style-type: none;  text-align: center;  width: 600px; margin-left: 0px;">
					FindMySong LLC &#169; Copyright 2013  All Rights Reserved
				</li>
			</ul>
		</div>
	</body>
</html>